#:schema node_modules/wrangler/config-schema.json
name = "controle-financeiro"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Habilitando o banco de dados D1 para desenvolvimento local
[[d1_databases]]
binding = "DB"                # Nome da variável de ambiente no código
database_name = "controle-financeiro-local-db" # Nome do banco de dados
database_id = "local"         # ID para desenvolvimento local

